sudo: required
services:
  - docker
before_install:
  - echo "BEFORE INSTALL START"
  - gem install bundler
  - docker build -t maqueda/demoapp .
  - echo "BEFORE INSTALL END"
script:
  - docker push maqueda/demoapp
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - 
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "demoapp"
  env: "Demoapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-704369017308"
  bucket_path: "demoapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY